version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .  # 如果 main.go 在根目录；否则写路径如 ./cmd/myapp

archives:
  - format: tar.gz
    # Windows 使用 zip
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{ .Os }}_{{ .Arch }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}
      {{ if .Mips }}_{{ .Mips }}{{ end }}

checksum:
  name: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Dean0731       # 替换为你的 GitHub 用户名
    name: tencent-cli-go       # 替换为你的仓库名
  draft: false

# 可选：打包额外文件
additional_files:
  - LICENSE
  - README.md